"""empty message

Revision ID: 985eee47e2ab
Revises: 5e51d243bc46
Create Date: 2022-10-13 23:26:18.902885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '985eee47e2ab'
down_revision = '5e51d243bc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'character_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.create_unique_constraint(None, 'characters', ['character_name'])
    op.alter_column('favoritescharacters', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favoritescharacters', 'character_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favoritesplanets', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favoritesplanets', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('planets', sa.Column('planet_name', sa.String(length=250), nullable=False))
    op.alter_column('planets', 'planet_population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'planet_diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'planets', ['planet_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planets', type_='unique')
    op.alter_column('planets', 'planet_diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'planet_population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('planets', 'planet_name')
    op.alter_column('favoritesplanets', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favoritesplanets', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favoritescharacters', 'character_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favoritescharacters', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'characters', type_='unique')
    op.alter_column('characters', 'character_name',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
